export const SAVE_MOVIES_TO_STORE = "SAVE_MOVIES_TO_STORE"
export const SET_MAXIMUM_AMOUNT_OF_MOVIES = "SET_MAXIMUM_AMOUNT_OF_MOVIES"

export const SAVE_FAVORITES_TO_STORE = "SAVE_FAVORITES_TO_STORE"
export const SET_MAXIMUM_AMOUNT_OF_FAVORITE_MOVIES =
  "SET_MAXIMUM_AMOUNT_OF_FAVORITE_MOVIES"
export const ADD_FAVORITE = "ADD_FAVORITE_TO_STORE"
export const REMOVE_FAVORITE = "ADD_FAVORITE_TO_STORE"

export const SAVE_BLOCKED_MOVIES_TO_STORE = "SAVE_BLOCKED_MOVIES_TO_STORE"
export const SAVE_BLOCKED_IDS_TO_STORE = "SAVE_BLOCKED_IDS_TO_STORE"
export const BLOCK_MOVIE = "BLOCK_MOVIE"
export const UNBLOCK_MOVIE = "UNBLOCK_MOVIE"

export const SAVE_GENRES_TO_STORE = "SAVE_GENRES_TO_STORE"
export const SET_SELECTED_GENRES = "SET_SELECTED_GENRES"

export const SET_LAST_PAGE = "SET_LAST_PAGE"
export const SET_NEW_AMOUNT = "SET_NEW_AMOUNT"

export const SET_LOADING = "SET_LOADING"
export const SET_ERROR = "SET_ERROR"
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE"

export const SET_USER = "SET_USER"
export const SET_TOKEN = "SET_TOKEN"
export const SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN"

export const RESET_STATE = "RESET_STATE"
