export const SAVE_MOVIES_TO_STORE = "SAVE_MOVIES_TO_STORE"

export const SAVE_FAVORITES_TO_STORE = "SAVE_FAVORITES_TO_STORE"
export const ADD_FAVORITE_TO_STORE = "ADD_FAVORITE_TO_STORE"

export const SAVE_GENRES_TO_STORE = "SAVE_GENRES_TO_STORE"

export const SET_NEW_PAGE = "SET_NEW_PAGE"
export const SET_NEW_AMOUNT = "SET_NEW_AMOUNT"

export const SET_SELECTED_GENRES = "SET_SELECTED_GENRES"

export const SET_USER = "SET_USER"
